### PR TITLE
Fixed PR title in CHANGELOG

### PR DESCRIPTION
**Pull request by szepeviktor**
Title of  #271

### CODE REVIEW

**Comment by szepeviktor** [comment]
@norberttech How should I know what title gets a nice big ✔️ ?

**Comment by norberttech** [comment]
This is now how the changelog works, you need to edit previous PR title, close this one and I will trigger [automation](https://github.com/aeon-php/automation) to regenerate changelog. 

In general, this action is not complaining about PR title but about PR content, which should be a HTML list of changes that later Automation can use to auto generate changelog. 

I'm closing this one since it can't be merged anyway.

**Comment by szepeviktor** [comment]
> you need to edit previous PR title

I've already done that: https://github.com/flow-php/etl/pull/271

**Comment by szepeviktor** [comment]
...but the CHANGELOG haven't changed: https://github.com/flow-php/etl/blob/1.x/CHANGELOG.md#changed

**Comment by norberttech** [comment]
Now it did, regenerating changelog requires me to trigger action manually

**Pull request closed without merging**
